<?php
/**
 * @file
 * Install file for D8UX
 */

/**
 * Implements hook_install().
 */
function d8ux_install() {
  // Be sure that this module is called last
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'd8ux')
    ->execute();

}

function d8ux_uninstall() {
  $variables = array(
    'd8ux_toolbar_edit_account_link',
    'd8ux_consistent_fieldsets',
  );

  foreach ($variables as $variable) {
    variable_del($variable);
  }
}

